# TODO: 아래 비어있는 내용을 추가해야 함
# 1. build 정보
# 2. 볼륨 마운트 정보

services:
  continuous_training_pipeline:
    build:
      context: 
      dockerfile:
    image: credit_score_classification:ct-pipeline-latest
    container_name: credit_score_classification_ct_pipeline
    volumes:
      - 
    environment:
      PYTHONPATH: /home/codespace
      ARTIFACTS_PATH: /home/codespace/artifacts
      FEATURE_STORE_URL: mysql+pymysql://root:root@mariadb:3306/mlops
    command: >
      python ${PYTHON_FILE} --model_name ${MODEL_NAME} --base_dt ${BASE_DT}
    networks:
      mlops_network:
networks:
  mlops_network:
    name: mlops_network
    external: true
