# TODO: 아래 비어있는 내용을 추가해야 함
# 1. build 정보
# 2. 볼륨 마운트 정보
# 3. 커맨드

services:
  bentoml_service:
    build:
      context: 
      dockerfile: 
    image: credit_score_classification-deploy:latest
    container_name: credit_score_classification_deploy
    volumes:
      - 
      - 
    environment:
      PYTHONPATH: /home/codespace
      ARTIFACTS_PATH: /home/codespace/artifacts
      FEATURE_STORE_URL: mysql+pymysql://root:root@mariadb:3306/mlops
    ports:
      - "3000:3000"
    command: >
      
    networks:
      mlops_network:
networks:
  mlops_network:
    name: mlops_network
    external: true
